version: 0.2
phases:
  pre_build:
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
      - docker-compose -f docker-compose.yml up
  build:
    commands:
      - mvn test -e -X
reports:
  Selenium:
    file-format: TestNG XML
    files:
      - target/surefire-reports/testng-results.xml
artifacts:
  files:
    - ./**/*
